version: '3.8'

services:
  db:
    image: mysql:5.7.37
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_USER=baha
      - MYSQL_PASSWORD=BaHa12062000
      - MYSQL_ROOT_PASSWORD=BaHa1206
      - MYSQL_DATABASE=motivation
    ports:
      [3306:3306]

  app:
    container_name: motivations
    build: .

    command: sh -c " python motivator/manage.py migrate && python motivator/manage.py runserver 0.0.0.0:8000"

    depends_on:
      - db

    volumes:
      - ./motivator:/motivator_motivations

    ports:
      [8000:8000]

volumes:
  mysql_data:
  motivator:
